# Generated by Django 5.0 on 2024-09-19 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_productreview_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='city',
            field=models.CharField(default='California', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='country',
            field=models.CharField(default='USA', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='zip_code',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
