# Generated by Django 5.0 on 2024-10-25 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_cartorder_oid_cartorder_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='product_status',
            field=models.CharField(choices=[('proccessing', 'Processing'), ('shipped', 'Shipped'), ('deliver', 'Deliver')], default='processing', max_length=30, null=True),
        ),
    ]
