# Generated by Django 5.0 on 2024-10-25 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_cartorder_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='product_status',
            field=models.CharField(blank=True, choices=[('proccessing', 'Processing'), ('shipped', 'Shipped'), ('deliver', 'Deliver')], default='processing', max_length=30, null=True),
        ),
    ]
