# Generated by Django 5.0 on 2024-10-25 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_cartorder_product_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='zip_code',
        ),
    ]
